### ISSUE TITLE
Missing information from Project page causes bug

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/pandora#115] opened 2019-01-22 08:13 UTC
If some of the fields from the project page (e.g. the researcher quote) are missing, Pandora throws a not-immediately comprehensible error.

**Comment by eatyourgreens** [comment] 2019-01-22 09:22
What was the error message? No problems here adding a new language to Diagnosis London. 
![Screenshot of Diagnosis London project details in the translations editor.](https://user-images.githubusercontent.com/59547/51524898-06e8f900-1e27-11e9-8884-adc672750c59.png)

**Comment by eatyourgreens** [comment] 2019-04-02 13:18
This might be a duplicate of #130.

**Comment by eatyourgreens** [comment] 2019-06-21 10:40
I'm pretty sure this was fixed by #134.

**Closed by eatyourgreens** 2019-06-21 10:40 UTC
